import { DRUM_KITS } from "../data/drumKits.js";

const uid = (prefix = "id") => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const emptySteps = () => Array.from({ length: 64 }, () => 0);

const defaultFx = () => ({
  inputGain: 1,
  eqEnabled: true,
  highpass: 20,
  lowpass: 18500,
  lowGain: 0,
  lowFrequency: 120,
  midGain: 0,
  midFrequency: 1200,
  midQ: 0.8,
  highGain: 0,
  highFrequency: 7000,
  compEnabled: true,
  compThreshold: -20,
  compKnee: 12,
  compRatio: 2.2,
  compAttack: 0.018,
  compRelease: 0.26,
  makeupGain: 1,
  multibandEnabled: false,
  multibandMix: 1,
  multibandLowCross: 180,
  multibandHighCross: 3200,
  multibandLowThreshold: -18,
  multibandMidThreshold: -20,
  multibandHighThreshold: -22,
  multibandLowRatio: 2.5,
  multibandMidRatio: 2.1,
  multibandHighRatio: 1.8,
  multibandLowAttack: 0.018,
  multibandMidAttack: 0.012,
  multibandHighAttack: 0.006,
  multibandLowRelease: 0.24,
  multibandMidRelease: 0.18,
  multibandHighRelease: 0.12,
  multibandLowMakeup: 1,
  multibandMidMakeup: 1,
  multibandHighMakeup: 1,
  saturationEnabled: true,
  drive: 0,
  chorusEnabled: true,
  chorusMix: 0,
  chorusRate: 0.25,
  chorusDepth: 0.006,
  timeShaperEnabled: false,
  timeShaperPattern: "straight",
  timeShaperDepth: 0.85,
  timeShaperMix: 1,
  timeShaperRate: 1,
  timeShaperSmooth: 0.012,
  pitchShiftEnabled: true,
  pitchShiftSemitones: 0,
  pitchShiftFine: 0,
  stereoEnabled: true,
  stereoWidth: 1,
  stereoPan: 0,
  delayEnabled: true,
  delaySync: true,
  delayDivision: "1/4",
  delayTime: 0.25,
  delayFeedback: 0.14,
  delayFeedbackHighpass: 120,
  delayTone: 6800,
  delayMix: 0,
  reverbEnabled: true,
  reverbRoom: "studio",
  reverbPreDelay: 0.008,
  reverbDamping: 7600,
  reverbMix: 0.045,
});

const drumTrack = (name, sampleId, color, steps) => ({
  id: uid("track"),
  name,
  type: "sampler",
  sampleId,
  autoNameFromSample: false,
  color,
  steps,
  mixer: { volume: 0.82, pan: 0 },
  effects: defaultFx(),
  pitch: 0,
  startOffset: 0,
  endOffset: 5,
  sampleAttack: 0.001,
  sampleRelease: 0.04,
  sampleCutoff: 20000,
  sampleResonance: 0.2,
  sampleFilterType: "lowpass",
  samplePan: 0,
  reverse: false,
  mute: false,
  solo: false,
  useArrangement: true,
  sequenceMode: "steps",
  notes: [],
});

const synthTrack = (name, presetId, color, notes) => ({
  id: uid("track"),
  name,
  type: "synth",
  presetId,
  autoNameFromSample: false,
  color,
  notes,
  synth: {},
  mixer: { volume: 0.68, pan: 0 },
  effects: defaultFx(),
  mute: false,
  solo: false,
  useArrangement: true,
  sequenceMode: "notes",
});

export function createBlankProject(samples = []) {
  const kit = DRUM_KITS[0];
  const kick = emptySteps();
  const snare = emptySteps();
  const hats = emptySteps();
  const percussion = emptySteps();

  [0, 8, 16, 24, 32, 40, 48, 56].forEach((step) => { kick[step] = 0.95; });
  [4, 12, 20, 28, 36, 44, 52, 60].forEach((step) => { snare[step] = 0.86; });
  for (let step = 0; step < 64; step += 2) hats[step] = step % 8 === 6 ? 0.72 : 0.48;
  [12, 28, 44, 60].forEach((step) => { percussion[step] = 0.62; });

  const tracks = [
    drumTrack("Kick", kit.slots.kick, "#ff9b6a", kick),
    drumTrack("Snare", kit.slots.snare, "#ff6ba8", snare),
    drumTrack("Closed Hat", kit.slots.closedHat, "#ffe27a", hats),
    drumTrack("Perc", kit.slots.perc, "#7af0c1", percussion),
    synthTrack("808 Bass", "preset-002", "#9f83ff", [
      { id: uid("note"), start: 0, duration: 7, midi: 36, velocity: 0.88 },
      { id: uid("note"), start: 8, duration: 7, midi: 36, velocity: 0.82 },
      { id: uid("note"), start: 16, duration: 7, midi: 39, velocity: 0.86 },
      { id: uid("note"), start: 24, duration: 7, midi: 34, velocity: 0.84 },
      { id: uid("note"), start: 32, duration: 7, midi: 36, velocity: 0.88 },
      { id: uid("note"), start: 40, duration: 7, midi: 43, velocity: 0.85 },
      { id: uid("note"), start: 48, duration: 7, midi: 39, velocity: 0.82 },
      { id: uid("note"), start: 56, duration: 7, midi: 34, velocity: 0.86 },
    ]),
    synthTrack("Warm Piano", "preset-026", "#64c8ff", [
      { id: uid("note"), start: 0, duration: 3, midi: 60, velocity: 0.72 },
      { id: uid("note"), start: 4, duration: 3, midi: 63, velocity: 0.66 },
      { id: uid("note"), start: 8, duration: 3, midi: 67, velocity: 0.72 },
      { id: uid("note"), start: 12, duration: 3, midi: 70, velocity: 0.64 },
    ]),
  ];

  return {
    id: uid("project"),
    name: "Untitled Hip-Hop Session",
    version: 8.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bpm: 142,
    swing: 0.16,
    key: 0,
    scale: "minor",
    masterVolume: 0.82,
    master: {
      inputGain: 1,
      eqEnabled: true,
      highpass: 22,
      lowpass: 19500,
      lowGain: 0.45,
      lowFrequency: 145,
      midGain: -0.9,
      midFrequency: 3250,
      midQ: 0.88,
      highGain: 0.42,
      highFrequency: 9800,
      multibandEnabled: true,
      multibandMix: 0.72,
      multibandLowCross: 180,
      multibandHighCross: 3200,
      multibandLowThreshold: -18,
      multibandMidThreshold: -20,
      multibandHighThreshold: -22,
      multibandLowRatio: 2.4,
      multibandMidRatio: 2,
      multibandHighRatio: 1.7,
      multibandLowMakeup: 1,
      multibandMidMakeup: 1,
      multibandHighMakeup: 1,
      compEnabled: true,
      compThreshold: -12,
      compRatio: 2,
      compKnee: 12,
      compAttack: 0.02,
      compRelease: 0.26,
      makeupGain: 1,
      saturationEnabled: true,
      clipDrive: 0.035,
      limiterCeiling: -1,
      engineQuality: "production",
      maxPolyphony: 84,
      trackPolyphony: 22,
      schedulerLookAheadMs: 155,
      renderSampleRate: 48000,
      renderCeiling: -1,
      renderLookAheadMs: 6,
      renderLimiterReleaseMs: 180,
      stereoEnabled: true,
      stereoWidth: 1.02,
      stereoPan: 0,
      delayEnabled: false,
      delaySync: true,
      delayDivision: "1/4",
      delayTime: 0.25,
      delayFeedback: 0.1,
      delayFeedbackHighpass: 120,
      delayTone: 7000,
      delayMix: 0,
      reverbEnabled: false,
      reverbRoom: "studio",
      reverbPreDelay: 0.008,
      reverbDamping: 7600,
      reverbMix: 0,
      timeShaperEnabled: false,
      timeShaperPattern: "straight",
      timeShaperDepth: 0,
      timeShaperMix: 0,
      timeShaperRate: 1,
      timeShaperSmooth: 0.012,
    },
    patternBars: 4,
    loopBars: 8,
    sampleEditor: { snap: 16, defaultSlices: 8 },
    samples,
    tracks,
    arrangement: tracks.map((track, index) => ({
      id: uid("clip"),
      trackId: track.id,
      startBar: 0,
      lengthBars: index < 4 ? 8 : 4,
      name: "Pattern A",
    })),
    automation: [],
    customPresets: [],
    selectedTrackId: tracks[0].id,
    selectedTrackIds: [tracks[0].id],
    view: "rack",
    playhead: 0,
  };
}

export function cloneProject(project) {
  const copy = JSON.parse(JSON.stringify(project));
  copy.id = uid("project");
  copy.name = `${project.name} Copy`;
  copy.createdAt = new Date().toISOString();
  copy.updatedAt = copy.createdAt;
  return copy;
}

export { uid, emptySteps, defaultFx };
